package com.example.util

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val displayName: String, val nativeName: String, val flag: String, val subtitle: String) {
    ENGLISH_US("English (US)", "Standard English", "🇺🇸", "Clean, official, standard UI terminology"),
    ENGLISH_INDIA("English (India)", "Desi English", "🇮🇳", "Regional Indian English slang & friendly tone"),
    CHRONICALLY_ONLINE("Chronically Online", "Brainrot & Meme Slang", "🌐", "Internet culture, Discord & TikTok slang")
}

/**
 * Dynamic dictionary data class holding all user-facing strings,
 * settings labels, and Gemini AI Studio parameter names.
 */
data class AppStrings(
    // App Bar & Main Navigation
    val appTitle: String,
    val appStyle: String,
    val photoToTask: String,
    val photoToTaskSubtitle: String,
    val insights: String,
    val scheduleExport: String,
    val rewardsAndBadges: String,
    val googleTasksSync: String,
    val account: String,

    // Home Screen & Stats
    val dailyMomentum: String,
    val completedSummary: String,
    val peakStreak: String,
    val allAgenda: String,
    val dailyHabits: String,
    val actionTasks: String,
    val allCategories: String,
    val noItemsTitle: String,
    val noItemsSubtitle: String,
    val addTaskButton: String,
    val pointsLabel: String,
    val levelLabel: String,

    // Task Items & Dialogs
    val addItemTitle: String,
    val editItemTitle: String,
    val itemTitlePlaceholder: String,
    val itemDescPlaceholder: String,
    val habitTypeToggle: String,
    val taskTypeToggle: String,
    val categoryLabel: String,
    val hourLabel: String,
    val minuteLabel: String,
    val durationLabel: String,
    val saveButton: String,
    val cancelButton: String,
    val closeButton: String,
    val applyAndClose: String,
    val deleteLabel: String,
    val syncCalendarLabel: String,
    val streakPill: String,

    // Settings Page
    val settingsTitle: String,
    val languageSectionTitle: String,
    val languageSectionDesc: String,
    val appStyleSectionTitle: String,
    val appStyleSectionDesc: String,
    val ambientGlowTitle: String,
    val ambientGlowToggle: String,
    val glowColorLabel: String,
    val appIconSwapperTitle: String,
    val appIconSwapperDesc: String,

    // Gemini AI Studio Parameter Names (Explicit Mapping)
    val geminiStudioTitle: String,
    val geminiApiKeyParam: String,
    val geminiRunPromptParam: String,
    val geminiTemperatureParam: String,
    val geminiTopKParam: String,
    val geminiTopPParam: String,
    val geminiModelParam: String,

    // Google Tasks Integration
    val googleTasksTitle: String,
    val googleTasksStatusConnected: String,
    val googleTasksStatusDisconnected: String,
    val googleTasksSyncNow: String,
    val googleTasksAutoSync: String,
    val googleTasksSyncSuccess: String,
    val googleTasksConnectAccount: String,

    // Firebase Auth
    val authTitle: String,
    val authSignIn: String,
    val authSignUp: String,
    val authSignOut: String,
    val authResetPassword: String,
    val authEmailPlaceholder: String,
    val authPasswordPlaceholder: String,
    val authGuestMode: String,
    val authWelcome: String,

    // Gamification
    val gamificationTitle: String,
    val gamificationPointsEarned: String,
    val gamificationLevelProgress: String,
    val gamificationBadgesTab: String,
    val gamificationLeaderboardTab: String,
    val gamificationGlobalRank: String,
    val gamificationFriendsRank: String,
    val gamificationStreakBonus: String
)

val EnglishUsStrings = AppStrings(
    appTitle = "HabitPulse",
    appStyle = "App Style",
    photoToTask = "Photo to Task",
    photoToTaskSubtitle = "Scan handwritten notes, whiteboards, or paper checklists",
    insights = "Habit Insights",
    scheduleExport = "Schedule Export",
    rewardsAndBadges = "Rewards & Badges",
    googleTasksSync = "Google Tasks Sync",
    account = "Account",

    dailyMomentum = "Daily Habit Momentum",
    completedSummary = "Completed Today",
    peakStreak = "Peak Streak",
    allAgenda = "All Items",
    dailyHabits = "Daily Habits",
    actionTasks = "Action Tasks",
    allCategories = "All Categories",
    noItemsTitle = "No items in this category",
    noItemsSubtitle = "Tap + or use Photo to Task to add items to your routine",
    addTaskButton = "Add Habit or Task",
    pointsLabel = "XP Points",
    levelLabel = "Level",

    addItemTitle = "Add Habit or Task",
    editItemTitle = "Edit Item",
    itemTitlePlaceholder = "e.g., Morning Deep Hydration",
    itemDescPlaceholder = "e.g., Drink 500ml water right after waking up",
    habitTypeToggle = "Daily Habit (Tracks Streaks)",
    taskTypeToggle = "Action Task (One-Off)",
    categoryLabel = "Category",
    hourLabel = "Hour (0-23)",
    minuteLabel = "Minute (0-59)",
    durationLabel = "Duration (m)",
    saveButton = "Save Item",
    cancelButton = "Cancel",
    closeButton = "Close",
    applyAndClose = "Apply & Close",
    deleteLabel = "Delete",
    syncCalendarLabel = "Sync to Google Calendar",
    streakPill = "d streak",

    settingsTitle = "Settings & Customization",
    languageSectionTitle = "Language & Localization",
    languageSectionDesc = "Switch regional English variants or internet slang to instantly update all UI labels and AI Studio parameters across the app.",
    appStyleSectionTitle = "App Style & Aesthetics",
    appStyleSectionDesc = "Select your preferred design language. Updates layout style and home screen launcher icon.",
    ambientGlowTitle = "Animated Ambient Glow",
    ambientGlowToggle = "Enable Ambient Glow Border",
    glowColorLabel = "Accent Glow Color",
    appIconSwapperTitle = "Dynamic Icon Swapper Active",
    appIconSwapperDesc = "Launcher icon synchronizes with chosen aesthetic",

    geminiStudioTitle = "Gemini AI Studio Configuration",
    geminiApiKeyParam = "Gemini API Key",
    geminiRunPromptParam = "Run Prompt",
    geminiTemperatureParam = "Temperature",
    geminiTopKParam = "Top-K",
    geminiTopPParam = "Top-P",
    geminiModelParam = "Model Version",

    googleTasksTitle = "Google Tasks Integration",
    googleTasksStatusConnected = "Connected to Google Tasks",
    googleTasksStatusDisconnected = "Not connected",
    googleTasksSyncNow = "Sync Now to Google Tasks",
    googleTasksAutoSync = "Auto-sync new tasks to Google Tasks",
    googleTasksSyncSuccess = "Tasks successfully synced to your Google Tasks list!",
    googleTasksConnectAccount = "Connect Google Account",

    authTitle = "User Authentication",
    authSignIn = "Sign In",
    authSignUp = "Create Account",
    authSignOut = "Sign Out",
    authResetPassword = "Reset Password",
    authEmailPlaceholder = "Email address",
    authPasswordPlaceholder = "Password",
    authGuestMode = "Continue as Guest",
    authWelcome = "Welcome back",

    gamificationTitle = "Trophy Room & Leaderboard",
    gamificationPointsEarned = "Total XP Earned",
    gamificationLevelProgress = "Level Progress",
    gamificationBadgesTab = "Milestone Badges",
    gamificationLeaderboardTab = "Leaderboard",
    gamificationGlobalRank = "Global Arena",
    gamificationFriendsRank = "Friends Circle",
    gamificationStreakBonus = "Streak Multiplier Active"
)

val EnglishIndiaStrings = AppStrings(
    appTitle = "HabitPulse",
    appStyle = "App Roop (Style)",
    photoToTask = "Photo se Task",
    photoToTaskSubtitle = "Whiteboard, diary ya notebook ka photo lo, AI kaam bana dega",
    insights = "Monthly Samiksha",
    scheduleExport = "Time-Table Export",
    rewardsAndBadges = "Inaam & Tamge",
    googleTasksSync = "Google Tasks Milaan",
    account = "Khata (Account)",

    dailyMomentum = "Aaj Ka Niyam & Raftaar",
    completedSummary = "Kaam Pura Hua",
    peakStreak = "Lamba Streak",
    allAgenda = "Saara Kaam",
    dailyHabits = "Roz ke Niyam (Habits)",
    actionTasks = "Zaroori Kaam (Tasks)",
    allCategories = "Saare Categories",
    noItemsTitle = "Idhar abhi koi kaam nahi hai boss",
    noItemsSubtitle = "+ dabao ya Photo se Task chala ke list banao",
    addTaskButton = "Naya Kaam / Niyam Jodo",
    pointsLabel = "Sikke (XP)",
    levelLabel = "Darja (Level)",

    addItemTitle = "Naya Niyam ya Kaam Jodo",
    editItemTitle = "Kaam Badlo",
    itemTitlePlaceholder = "Jaise: Subah 2 glass paani peena",
    itemDescPlaceholder = "Jaise: Uthte hi pehle paani peena bina phone dekhe",
    habitTypeToggle = "Roz Ka Niyam (Streak chalega)",
    taskTypeToggle = "Ek Baar Ka Kaam (Task)",
    categoryLabel = "Vibhag (Category)",
    hourLabel = "Ghanta (0-23)",
    minuteLabel = "Minute (0-59)",
    durationLabel = "Kitna time lagega (m)",
    saveButton = "Pakka Karo (Save)",
    cancelButton = "Chhodo (Cancel)",
    closeButton = "Band Karo",
    applyAndClose = "Lagao & Band Karo",
    deleteLabel = "Hatao",
    syncCalendarLabel = "Google Calendar mein daalo",
    streakPill = "din ka streak",

    settingsTitle = "Settings (Pura Control)",
    languageSectionTitle = "Bhasha & Desi Style",
    languageSectionDesc = "Bhasha badlo aur dekho pura app instant Desi English mein change ho jayega bina reload kiye!",
    appStyleSectionTitle = "App Roop & Look",
    appStyleSectionDesc = "Apna manpasand look chuno. App icon aur theme dono turant badal jayenge.",
    ambientGlowTitle = "Chamkila Glow Effect",
    ambientGlowToggle = "Ambient Glow border on rakhein",
    glowColorLabel = "Glow Rang",
    appIconSwapperTitle = "Desi Launcher Icon Swapper",
    appIconSwapperDesc = "Home screen icon style ke hisaab se set hai",

    // Gemini AI Studio parameters mapped for English (India)
    geminiStudioTitle = "Gemini AI Studio Setting",
    geminiApiKeyParam = "Gemini API Key (Keep it safe da)",
    geminiRunPromptParam = "Chalao",
    geminiTemperatureParam = "Creativity Level",
    geminiTopKParam = "Top Candidates (Jugaad)",
    geminiTopPParam = "Confidence Shuruat",
    geminiModelParam = "Gemini Model Variant",

    googleTasksTitle = "Google Tasks Milaan",
    googleTasksStatusConnected = "Google Tasks ke sath linked hai guru",
    googleTasksStatusDisconnected = "Linked nahi hai",
    googleTasksSyncNow = "Abhi Sync Karo (Google Tasks)",
    googleTasksAutoSync = "Naye tasks apne aap Google Tasks mein bhejo",
    googleTasksSyncSuccess = "Badhiya! Saare tasks Google Tasks mein sync ho gaye!",
    googleTasksConnectAccount = "Google Khata Jodo",

    authTitle = "Apna Khata (Login / Signup)",
    authSignIn = "Andar Aao (Sign In)",
    authSignUp = "Naya Khata Banao (Sign Up)",
    authSignOut = "Bahar Niklo (Sign Out)",
    authResetPassword = "Password Bhool Gaye?",
    authEmailPlaceholder = "Email pata",
    authPasswordPlaceholder = "Gupt Code (Password)",
    authGuestMode = "Guest banke chalao",
    authWelcome = "Swagat hai wapas",

    gamificationTitle = "Tamga & Muqabla Room",
    gamificationPointsEarned = "Kul Sikke (Total XP)",
    gamificationLevelProgress = "Agla Darja Progress",
    gamificationBadgesTab = "Jeete Hue Tamge (Badges)",
    gamificationLeaderboardTab = "Dost-Yaar Board",
    gamificationGlobalRank = "Desh-Videsh Rank",
    gamificationFriendsRank = "Apne Yaar Dost",
    gamificationStreakBonus = "Streak Dhamaka Active"
)

val ChronicallyOnlineStrings = AppStrings(
    appTitle = "HabitPulse",
    appStyle = "Drip / App Aesthetic",
    photoToTask = "Optical Drop (Photo to Task)",
    photoToTaskSubtitle = "Snap IRL lore, notes or receipts to spawn instant side quests",
    insights = "Monthly Lore Breakdown",
    scheduleExport = "Timetable Meta Drop",
    rewardsAndBadges = "Clout & Flex Badges",
    googleTasksSync = "Google Tasks Uplink",
    account = "Main Character ID",

    dailyMomentum = "Main Character Momentum",
    completedSummary = "Quests Cleared Today",
    peakStreak = "God-Tier W Streak",
    allAgenda = "All Quests",
    dailyHabits = "Daily Rituals (No Cap)",
    actionTasks = "Side Quests",
    allCategories = "Quest Archetypes",
    noItemsTitle = "Zero quests detected in this realm",
    noItemsSubtitle = "Hit + or drop an optical scan to cook up new habits fr fr",
    addTaskButton = "Spawn New Quest",
    pointsLabel = "Clout Points (XP)",
    levelLabel = "Power Level",

    addItemTitle = "Forge Quest / Daily Ritual",
    editItemTitle = "Mod Quest Specs",
    itemTitlePlaceholder = "e.g., Hydrate before doomscrolling",
    itemDescPlaceholder = "e.g., Chug 500ml H2O before touching TikTok on god",
    habitTypeToggle = "Daily Ritual (Builds W Streaks)",
    taskTypeToggle = "One-Off Side Quest",
    categoryLabel = "Archetype",
    hourLabel = "Spawn Hour (0-23)",
    minuteLabel = "Minute (0-59)",
    durationLabel = "Raid Duration (m)",
    saveButton = "Lock It In",
    cancelButton = "Bail Out",
    closeButton = "Dismiss",
    applyAndClose = "Lock In & Roll",
    deleteLabel = "Yeet Task",
    syncCalendarLabel = "Drop into Google Calendar",
    streakPill = "d W streak",

    settingsTitle = "Side Quest Config",
    languageSectionTitle = "Brainrot & Slang Dialect",
    languageSectionDesc = "Switch dialects to instantly recalibrate all UI lore, sidequest labels, and AI Studio parameters in real-time.",
    appStyleSectionTitle = "UI Drip & Visual Vibe",
    appStyleSectionDesc = "Switch aesthetic engines. Swaps launcher icon and visual aura instantly on god.",
    ambientGlowTitle = "RGB Gamer Ambient Glow",
    ambientGlowToggle = "Enable Neon Aura Glow",
    glowColorLabel = "Aura Frequency",
    appIconSwapperTitle = "Dynamic Icon Skinning",
    appIconSwapperDesc = "Launcher drip automatically synched",

    // Gemini AI Studio parameters mapped for Chronically Online mode
    geminiStudioTitle = "Gemini AI Studio Engine",
    geminiApiKeyParam = "Secret Lore / Token Drop",
    geminiRunPromptParam = "Let Him Cook",
    geminiTemperatureParam = "Cooking Index",
    geminiTopKParam = "Vibe Check / Randomness",
    geminiTopPParam = "Canon Probability Filter",
    geminiModelParam = "Model Lore Branch",

    googleTasksTitle = "Google Tasks Uplink",
    googleTasksStatusConnected = "Locked & Linked to Google Tasks",
    googleTasksStatusDisconnected = "No Uplink Found",
    googleTasksSyncNow = "Sync Quests to Google Tasks",
    googleTasksAutoSync = "Auto-push spawned quests to Google Tasks",
    googleTasksSyncSuccess = "Huge W! All side quests beamed to Google Tasks fr fr!",
    googleTasksConnectAccount = "Link Google Identity",

    authTitle = "Main Character Auth",
    authSignIn = "Log In (Spawn In)",
    authSignUp = "Create Character Profile",
    authSignOut = "Despawn (Log Out)",
    authResetPassword = "Lost Password Lore?",
    authEmailPlaceholder = "Digital comms (Email)",
    authPasswordPlaceholder = "Secret keycode",
    authGuestMode = "Speedrun as NPC Guest",
    authWelcome = "Welcome back king",

    gamificationTitle = "Flex Chamber & Leaderboard",
    gamificationPointsEarned = "Total XP Harvested",
    gamificationLevelProgress = "Ascension Progress",
    gamificationBadgesTab = "Rare Achievement Badges",
    gamificationLeaderboardTab = "Clout Standings",
    gamificationGlobalRank = "Global Ranked Lobby",
    gamificationFriendsRank = "Squad / Mutuals",
    gamificationStreakBonus = "Streak Buff: 2.5x Multiplier"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH_US -> EnglishUsStrings
        AppLanguage.ENGLISH_INDIA -> EnglishIndiaStrings
        AppLanguage.CHRONICALLY_ONLINE -> ChronicallyOnlineStrings
    }
}

val LocalAppStrings = compositionLocalOf { EnglishUsStrings }
val LocalAppLanguage = compositionLocalOf { AppLanguage.ENGLISH_US }
